// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpOvT6t8Nq1qcL2xYbNJSHf3s6_0WnVqw',
    appId: '1:393235522421:web:73f04a46dd5c3dfe7ba93c',
    messagingSenderId: '393235522421',
    projectId: 'brain-hacker-de2c5',
    authDomain: 'brain-hacker-de2c5.firebaseapp.com',
    storageBucket: 'brain-hacker-de2c5.appspot.com',
    measurementId: 'G-Z46W1SDKYB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg5zbqkQd6dwecDHo5pF03SOJnTq-YJQs',
    appId: '1:393235522421:android:6a665460c5e47dd17ba93c',
    messagingSenderId: '393235522421',
    projectId: 'brain-hacker-de2c5',
    storageBucket: 'brain-hacker-de2c5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlEeJRExmlz41DIrAggdqO9ED4WRMZMtk',
    appId: '1:393235522421:ios:430b0d8ddd18dfb47ba93c',
    messagingSenderId: '393235522421',
    projectId: 'brain-hacker-de2c5',
    storageBucket: 'brain-hacker-de2c5.appspot.com',
    iosClientId:
        '393235522421-mku4d98f9msfipl317av2crfg19das96.apps.googleusercontent.com',
    iosBundleId: 'com.example.videoApp',
  );
}
